### ISSUE TITLE
Need more detailed document

### ISSUE THREAD

**Issue by sivabe35** [lopspower/RxAnimation#3]
Looks great but this library is really Hard to Implement

**Comment by lopspower** [comment]
Yes Rx is a rather complex library. And this library requires a mastery of Rx before it can be used. If this is the case, the few examples present in the Readme are usually sufficient since it is Rx that is complex and not this library. Nevertheless, if the examples are not enough do not hesitate to open an exit it is with pleasure that I will help :).
